### ISSUE TITLE
createFromParcel does not use correct ClassLoaders

### ISSUE THREAD

**Issue by sweggersen** [rharter/auto-value-parcel#70] opened 2016-06-11 21:02 UTC
This is whats being generated:

    @Override
    public AutoValue_Entry createFromParcel(Parcel in) {
      ClassLoader cl = AutoValue_Entry.class.getClassLoader();
      return new AutoValue_Entry(
          in.readString(),
          (EntryAccount) in.readParcelable(cl),
          in.readInt() == 0 ? (EntryLogo) in.readParcelable(cl) : null
      );
    }

The generated method uses the Entry ClassLoader for both objects, but both EntryAccount and EntryLogo should use their own ClassLoader.

This is the exception I get when trying to use the Parcelable in an Intent.
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: AutoValue_Entry
So, I'm guessing this is the problem.

This is my Entry class (I'm using this library alongside auto-value-gson) :

    @AutoValue
    public abstract class Entry implements Parcelable {

        @SerializedName("introduction") abstract public String introduction();
        @SerializedName("account") abstract public EntryAccount account();
        @SerializedName("logo") @Nullable abstract public EntryLogo logo();

        public static TypeAdapter<Entry> typeAdapter(Gson gson) {
            return new AutoValue_Entry.GsonTypeAdapter(gson);
        }

    }

What could be the problem

**Comment by JakeWharton** [comment] 2016-06-13 20:56
You outlined the problem pretty clearly. The fix is trivial. I'll try to send it tonight or tomorrow unless someone beats me to it.

**Comment by johncarl81** [comment] 2016-06-14 04:17
Using the target property's classloader will trigger a `BadParcelableException` in cases where you use android classes, like `Parcelable`:
```java
@AutoValue
public abstract class Entry implements Parcelable {
    public abstract Parcelable value();
    public static Entry build(Parcelable input) {
        return new AutoValue_Entry(input);
    }
}
```
Throws exception:
```java
intent.putExtra(SecondActivity.EXTRA_ENTRY, Entry.build(EntryAccount.build()));
...
getIntent().getExtras().getParcelable(EXTRA_ENTRY); // <- here
```

Digging into this a bit, I'm not able to reproduce the error (although I can't get auto-value-gson to work atm), and the ClassLoader usage seems appropriate to me.  Is there some detail with the auto-value-gson or overall project configuration that could be causing this error?

**Comment by rharter** [comment] 2016-06-14 13:14
It depends on your class loader setup, multidex, etc. We're working on a fix for this issue.

**Closed** 2016-06-16 02:22 UTC

**Comment by tomxor** [comment] 2016-08-01 22:17
@rharter I think that's still (v0.2.3-rc2) the case for `Map` types, as it always uses the `ClassLoader` of the value.

This:
```java
@AutoValue public abstract class Foo implements Parcelable {
  public static Foo create(Map<Bar, String> map) {
    return new AutoValue_Foo(map);
  }

  public abstract Map<Bar, String> map();
}
```

Generates the following:
```java
(Map<Bar, String>) in.readHashMap(String.class.getClassLoader())
```

In my case `Bar` is an Enum and that leads to a `ClassNotFoundException`:
```
Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = avp.example.Bar)
```

**Comment by rharter** [comment] 2016-08-01 23:18
There was some heavy discussion around this, and we chose to go with the value in a map, since we can only choose one and can't know which to use. I supposed we could choose the value 's classloaders if it's not a built-in, otherwise choose the let's classloader, but that would still fail in cases like `Map<Foo, Bar>` where `Foo` and `Bar` are on different classloaders.

**Comment by tomxor** [comment] 2016-08-01 23:19
how about providing a way to control the type with a custom annotation?

**Comment by JakeWharton** [comment] 2016-08-01 23:22
> but that would still fail in cases like Map<Foo, Bar> where Foo and Bar are on different classloaders.

I'd be curious if this ever happens. I'm supportive of your proposal vs. making it configurable since I don't think that case exists.

**Comment by rharter** [comment] 2016-08-02 04:33
Thats true. I was surprised to hear that this case happens, since usually it's the value that is the exotic type. I think the proposal above is fair and will cover most of the cases.

I don't want to add an annotation to choose the classloaders, as if it's really an issue you can just use a TypeAdapter to Parcel it manually. (you can also do that for this case for now).

**Comment by rharter** [comment] 2016-08-02 14:23
Looking over this again, the current code is valid.  The [documentation](https://developer.android.com/reference/android/os/Parcel.html) for `writeMap` reads "The Map keys must be String objects", and the code reflects the same.
