### ISSUE TITLE
Class not found when unmarshalling

### ISSUE THREAD

**Issue by vigukalai** [rharter/auto-value-parcel#103] opened 2016-12-22 11:17 UTC
Class not found when unmarshalling: com.sample.dev.activity.AutoValue_HomeScreenActivity_UIState
                                                             java.lang.ClassNotFoundException: com.sample.dev.activity.AutoValue_HomeScreenActivity_UIState
                                                                 at java.lang.Class.classForName(Native Method)
                                                                 at java.lang.Class.forName(Class.java:309)
                                                                 at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
                                                                 at android.os.Parcel.readParcelable(Parcel.java:2245)
                                                                 at com.sample.dev.AutoValue_AppNavigator_NavigationToken$1.createFromParcel(AutoValue_AppNavigator_NavigationToken.java:15)
                                                                 at com.sample.dev.AutoValue_AppNavigator_NavigationToken$1.createFromParcel(AutoValue_AppNavigator_NavigationToken.java:9)
                                                                 at android.os.Parcel.readParcelable(Parcel.java:2252)
                                                                 at android.os.Parcel.readValue(Parcel.java:2152)
                                                                 at android.os.Parcel.readListInternal(Parcel.java:2526)
                                                                 at android.os.Parcel.readArrayList(Parcel.java:1842)
                                                                 at android.os.Parcel.readValue(Parcel.java:2173)
                                                                 at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                                                 at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                 at android.os.Bundle.getParcelable(Bundle.java:755)
                                                                 at com.sample.dev.activity.ProfileActivity.onCreate(ProfileActivity.java:86)
                                                                 at android.app.Activity.performCreate(Activity.java:6088)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2416)
                                                                 at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5300)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

This happens when it try pass parcelable data through intent to start another activity. I am using latest version of auto-value and auto-value-parcel libraries. Kindly help me.

**Comment by JakeWharton** [comment] 2016-12-22 14:44
Why do you think this library is the cause? Is the class in your app?

**Comment by vigukalai** [comment] 2016-12-22 14:46
Yes. The class is present in app.

**Comment by rharter** [comment] 2016-12-22 14:53
Is there something you see in the generated code (`AutoValue_HomeScreenActivity_UIState`) that seems wrong?

**Comment by JakeWharton** [comment] 2016-12-22 14:53
Unless the generated code is malformed the presence of the class in your
app rules out this library as the cause.

**Comment by vigukalai** [comment] 2016-12-22 14:56
final class AutoValue_AppNavigator_NavigationToken extends $AutoValue_AppNavigator_NavigationToken {
  public static final Parcelable.Creator<AutoValue_AppNavigator_NavigationToken> CREATOR = new Parcelable.Creator<AutoValue_AppNavigator_NavigationToken>() {
    @Override
    public AutoValue_AppNavigator_NavigationToken createFromParcel(Parcel in) {
      return new AutoValue_AppNavigator_NavigationToken(
          in.readInt(),
          in.readBundle(Bundle.class.getClassLoader()),
          in.readParcelable(Parcelable.class.getClassLoader())
      );
    }

 @AutoValue
    public abstract static class NavigationToken implements Parcelable {
        public abstract int activityType();
        public abstract Bundle launchExtras();
        @Nullable
        public abstract Parcelable token();

 public static NavigationToken create(int activityType, Bundle launchExtras,Parcelable token) {
            return new AutoValue_AppNavigator_NavigationToken(activityType, launchExtras,token);
        }

Here the value for token is HomeScreenActivity_UIState class.

**Comment by rharter** [comment] 2016-12-22 15:02
That's not the class in question.  The error message says that `AutoValue_HomeScreenActivity_UIState` is not found.  Does that class exist in your app?  (Would be in your build folder)

**Comment by vigukalai** [comment] 2016-12-22 15:07
Yes. The class is present in build folder. For your information the code was working fine until I update the libraries. ie. auto-value and auto-value-parcel. I opened issue to know whether I need to change anything in creating class.

**Comment by vigukalai** [comment] 2016-12-22 15:11
One of my attempt that worked is instead of Parcelable in above code if I give HomeScreenActivity_UIState and build the class, it works fine and I can navigate to the activity. Reason I used to Parcelable is I have many UIState that relate to different activity.

**Comment by rharter** [comment] 2016-12-22 15:15
Do you use mutlidex on this project?

**Comment by vigukalai** [comment] 2016-12-22 15:15
@rharter  Yes. I am using multidex.

**Comment by rharter** [comment] 2016-12-22 15:18
Okay, my suspicion is that your `AutoValue_HomeScreenActivity_UIState` needs a different `ClassLoader` than the one for `Parcelable`, so it can't find the class on the provided classloader.

A better solution to this problem would probably be to use generics to ensure that the generated code is using the correct class loader.

```java
@AutoValue
public abstract static class NavigationToken<T> implements Parcelable {
    public abstract int activityType();
    public abstract Bundle launchExtras();
    @Nullable public abstract T token();

  public static NavigationToken create(int activityType, Bundle launchExtras, T token) {
    return new AutoValue_AppNavigator_NavigationToken(activityType, launchExtras, token);
  }
```

**Comment by vigukalai** [comment] 2016-12-22 15:28
When I use above code I get error:
Error:(1039, 85) error: non-static type variable T cannot be referenced from a static context
Error:(1031, 29) error: AutoValue property token is not a supported Parcelable type.

**Comment by rharter** [comment] 2016-12-22 15:41
Add the `<T>`.  

I'm going to close this issue since it's not an `auto-value-parcel` issue.  Feel free to reopen if you find that you can fix up the generated code to make this work.

**Closed by rharter** 2016-12-22 15:41 UTC

**Comment by glidodroid** [comment] 2017-02-07 10:22
@rharter Could you please **delete** the second comment is issue 103 which is "Why do you think this library is the cause? Is the class in your app?" posted by JakeWharton. While opening the issue I have included unnecessary package name in that error which is posted and his comment has link to my issue. Those package name I should not have mentioned. Help me out pls.

**Comment by rharter** [comment] 2017-02-07 15:45
@glidodroid I've removed that comment so the package name isn't in public anymore.

**Comment by glidodroid** [comment] 2017-02-07 16:07
@rharter Thanks a Lot.

**Comment by Tagakov** [comment] 2017-06-02 18:57
Does using Thread.currentThread().getContextClassLoader() have any drawbacks and can it be used instead of ClassLoader obtained from Class of parcelable?

instead of 
`
in.readParcelable(AnyClass.class.getClassLoader())
`
you can use
`
in.readParcelable(Thread.currentThread().getContextClassLoader())
`

Using class loader obtained in the first way may lead to ClassNotFoundException if classloader obtained from system class (like Parcelable) and multidex is presented.

`
@AutoValue
abstract class MyClass implements Parcelable {
 abstract Parcelable data();
}
`
